# Generated by Django 6.0.4 on 2026-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='cumul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='pourcentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
